(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='ZEN_STATE_V1';
const defaultState={lang:'fr',theme:'dark',wallpaper:'',labels:{notes:'note idée',projects:'projet',motivation:'motivation'},notes:[{id:1,text:'Construire ZEN en PWA',important:true,created:Date.now()}],projects:[],quotes:[]};
let state=load();
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}'),labels:{...defaultState.labels,...(JSON.parse(localStorage.getItem(KEY)||'{}').labels||{})}}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function t(k){return (ZEN_I18N[state.lang]||ZEN_I18N.fr)[k]||k}
function applySettings(){document.documentElement.lang=state.lang;document.body.classList.toggle('light',state.theme==='light');const bg=state.wallpaper||"url('assets/wallpaper-default.jpg')";document.querySelector('.background').style.backgroundImage=`linear-gradient(rgba(20,17,25,.08),rgba(20,17,25,.25)),${state.wallpaper?`url('${state.wallpaper}')`:`url('assets/wallpaper-default.jpg')`}`;$$('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;el.textContent=t(k)});$$('[data-theme]').forEach(b=>b.classList.toggle('selected',b.dataset.theme===state.theme));$$('[data-lang]').forEach(b=>b.classList.toggle('selected',b.dataset.lang===state.lang));
  $$('[data-rename]').forEach(b=>{const key=b.dataset.rename;const label=b.closest('.section-title').querySelector('[data-i18n]'); if(label) label.textContent=state.labels[key]||t(key)});
}
function navigate(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name)); if(name==='notes')renderNotes(); if(name==='projects')renderProjects(); if(name==='motivation')renderQuotes()}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.go)));
function tick(){const d=new Date(),h=d.getHours(),m=d.getMinutes(),s=d.getSeconds(),ms=d.getMilliseconds();const time=`${h}:${String(m).padStart(2,'0')}`;$$('[data-time]').forEach(el=>el.textContent=time);document.querySelectorAll('.watch').forEach(w=>{const hour=((h%12)+m/60+s/3600)*30,minute=(m+s/60)*6,second=(s+ms/1000)*6;const hh=w.querySelector('.hand.hour'),mm=w.querySelector('.hand.minute'),ss=w.querySelector('.hand.second');if(hh)hh.style.transform=`translate(-50%,-90%) rotate(${hour}deg)`;if(mm)mm.style.transform=`translate(-50%,-90%) rotate(${minute}deg)`;if(ss)ss.style.transform=`translate(-50%,-90%) rotate(${second}deg)`})}
setInterval(tick,80);tick();
function renderNotes(filter='all'){const list=$('#notes-list');if(!list)return;const notes=filter==='important'?state.notes.filter(n=>n.important):state.notes;list.innerHTML=notes.length?notes.slice().sort((a,b)=>b.created-a.created).slice(0,7).map(n=>`<div class="note-row"><div><div class="note-text">${esc(n.text)}</div><div class="note-meta">${new Date(n.created).toLocaleDateString(state.lang==='fr'?'fr-FR':'en-US')}</div></div><div class="note-actions"><button class="note-toggle ${n.important?'important':''}" data-id="${n.id}" aria-label="important"></button><button class="note-delete" data-del-note="${n.id}">×</button></div></div>`).join(''):`<div class="empty">${t(filter==='important'?'emptyNotes':'emptyNotes')}</div>`}
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>renderNotes(b.dataset.filter)));
function renderProjects(){const el=$('#projects-list');if(!el)return;if(!state.projects.length){el.innerHTML=`<div class="empty">${t('emptyProjects')}</div>`;return}el.innerHTML=state.projects.map(p=>`<button class="project-card" data-project="${p.id}"><span class="project-folder"></span><span><h3>${esc(p.name)}</h3><p>${p.notes?.length||0} ${state.lang==='fr'?'note(s)':'note(s)'} · ${p.photos?.length||0} photo(s)</p></span></button>`).join('')}
function renderQuotes(){const el=$('#quotes-list');if(!el)return;el.innerHTML=state.quotes.length?state.quotes.map(q=>`<div class="quote-card"><span>“${esc(q)}”</span><button data-del-quote="${encodeURIComponent(q)}">×</button></div>`).join(''):`<div class="empty">${t('emptyQuotes')}</div>`}
function openModal(title,html,submit){$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;$('#modal').classList.remove('hidden');const f=$('#modal-form');if(f)f.addEventListener('submit',e=>{e.preventDefault();submit(new FormData(f));closeModal()})}
function closeModal(){$('#modal').classList.add('hidden')}
$('#modal-close').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
$('#add-note').addEventListener('click',()=>openModal(t('newNote'),`<form id="modal-form"><textarea name="text" placeholder="${t('notePlaceholder')}" required></textarea><button class="modal-submit">${t('save')}</button></form>`,fd=>{state.notes.push({id:Date.now(),text:fd.get('text').trim(),important:false,created:Date.now()});save();renderNotes()}));
$('#add-project').addEventListener('click',()=>openModal(t('newProject'),`<form id="modal-form"><input name="name" placeholder="${t('projectPlaceholder')}" required><textarea name="notes" placeholder="${t('projectNotes')}"></textarea><label class="wallpaper-button">Photo<input name="photo" type="file" accept="image/*"></label><button class="modal-submit">${t('save')}</button></form>`,async fd=>{const p={id:Date.now(),name:fd.get('name').trim(),notes:fd.get('notes')?[fd.get('notes').trim()]:[],photos:[]};const file=fd.get('photo');if(file&&file.size)p.photos=[await fileToData(file)];state.projects.push(p);save();renderProjects()}));
document.querySelector('#projects-list').addEventListener('click',e=>{
 const card=e.target.closest('[data-project]'); if(!card)return;
 const p=state.projects.find(x=>x.id==card.dataset.project); if(!p)return;
 const available=state.notes.map(n=>`<label style="display:flex;gap:9px;align-items:center;margin:8px 0"><input type="checkbox" name="noteIds" value="${n.id}" ${p.notes.includes(n.text)?'checked':''}> <span>${esc(n.text)}</span></label>`).join('') || `<div class="note-meta">${t('emptyNotes')}</div>`;
 const photos=(p.photos||[]).map(src=>`<img src="${src}" style="width:72px;height:72px;object-fit:cover;border-radius:12px">`).join('');
 openModal(esc(p.name),`<form id="modal-form"><b>${t('projectNotes')}</b><div style="margin:10px 0 16px">${available}</div><label class="wallpaper-button" style="display:inline-block;margin-bottom:14px">Photo<input name="photo" type="file" accept="image/*"></label><div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:15px">${photos}</div><button class="modal-submit">${t('save')}</button></form>`,async fd=>{
   const ids=fd.getAll('noteIds').map(Number); p.notes=state.notes.filter(n=>ids.includes(Number(n.id))).map(n=>n.text);
   const file=fd.get('photo'); if(file&&file.size)p.photos=[...(p.photos||[]),await fileToData(file)]; save(); renderProjects();
 });
});
$('#add-quote').addEventListener('click',()=>openModal(t('newQuote'),`<form id="modal-form"><textarea name="quote" placeholder="${t('quotePlaceholder')}" required></textarea><button class="modal-submit">${t('save')}</button></form>`,fd=>{state.quotes.push(fd.get('quote').trim());save();renderQuotes()}));
$('#notes-list').addEventListener('click',e=>{const toggle=e.target.closest('[data-id]');if(toggle){const n=state.notes.find(x=>x.id==toggle.dataset.id);if(n){n.important=!n.important;save();renderNotes()}}const del=e.target.closest('[data-del-note]');if(del){state.notes=state.notes.filter(n=>n.id!=del.dataset.delNote);save();renderNotes()}});
$('#quotes-list').addEventListener('click',e=>{const d=e.target.closest('[data-del-quote]');if(d){const q=decodeURIComponent(d.dataset.delQuote);state.quotes=state.quotes.filter(x=>x!==q);save();renderQuotes()}});
$$('[data-rename]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.rename;openModal(t('rename'),`<form id="modal-form"><input name="name" value="${esc(state.labels[key])}" required><button class="modal-submit">${t('save')}</button></form>`,fd=>{state.labels[key]=fd.get('name').trim();save();applySettings()})}));
$$('[data-theme]').forEach(b=>b.addEventListener('click',()=>{state.theme=b.dataset.theme;save();applySettings()}));$$('[data-lang]').forEach(b=>b.addEventListener('click',()=>{state.lang=b.dataset.lang;save();applySettings();renderNotes();renderProjects();renderQuotes()}));
$('#wallpaper-input').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;state.wallpaper=await compressImage(file);save();applySettings()});
$('#reset-data').addEventListener('click',()=>{if(confirm(t('confirmReset'))){state={...structuredClone(defaultState),lang:state.lang,theme:state.theme,wallpaper:state.wallpaper};save();applySettings();renderNotes();renderProjects();renderQuotes();alert(t('resetDone'))}});
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fileToData(file){return new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(file)})}
function compressImage(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>{const im=new Image();im.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=im.width*scale;c.height=im.height*scale;c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.78))};im.onerror=reject;im.src=fr.result};fr.onerror=reject;fr.readAsDataURL(file)})}
applySettings();renderNotes();renderProjects();renderQuotes();
setTimeout(()=>$('#splash').classList.add('hidden'),1450);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
})();
